# Generated by Django 4.0.3 on 2022-04-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Author',
        ),
    ]
