# Generated by Django 4.0.3 on 2022-04-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='qty',
        ),
    ]
