# Generated by Django 4.0.3 on 2022-04-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_author_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
