# Generated by Django 4.0.3 on 2022-04-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
